name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Use Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
        env:
          SLACK_WEBHOOK_URL: https://example.com
          CI: true
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
